export enum ActionType {
    MOUNT = 'MOUNT',
    TOGGLE = 'TOGGLE',
    SET_LOG_INFO = 'SET_LOG_INFO',
    ADD_TO_BASKET = 'ADD_TO_BASKET',
    UPDATE_BASKET = 'UPDATE_BASKET',
    REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET',
    SET_USER = 'SET_USER',
    LOGOUT_USER = 'LOGOUT_USER',
    TOGGLE_LOADING = 'TOGGLE_LOADING',
}
